import Head from 'next/head';
import { Header } from '../../components/header';
import styles from './topics.module.css';

export default function Playful() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HCI Portfolio | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>Playful Interactions</h1>
        <>
          <h2>Assignments</h2>
          <h3>A. New Playful Interaction Concept</h3>
          <p>The new concept described.</p>

          <h3>B. Research</h3>
          <p>Some research stuff</p>

          <h3>C. Reflection</h3>
          <p>Reflection</p>
        </>
        <>
          <h2>Research</h2>
        </>
        <>
          <h2>Reflect</h2>
        </>
      </main>
    </div>
  )
}
