import Head from 'next/head'
import { Header } from '../components/header'
import styles from '../styles/Home.module.css'

export default function Labweeks() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HCI Portfolio | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>Lab Weeks</h1>
      </main>
    </div>
  )
}
