import Head from 'next/head'
import { Header } from '../../components/header'
import styles from './workshops.module.css';

export default function ComputerVision() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HCI Portfolio | Julian van Beek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>Computer Vision</h1>
        <>
          <h2>Assignments</h2>
          <h3>Portfolio assignment 7</h3>
          <p>Info about the assignment</p>
          <h3>Portfolio assignment 8</h3>
          <p>Info about the assignment</p>
          <h3>Portfolio assignment 9</h3>
          <p>Info about the assignment</p>
        </>
      </main>
    </div>
  )
}
